theme: jekyll-theme-minimal

"""
title: Poster Session of the 2nd Computer Science Workshop @ DIBRIS.
description: [Welcome to the virtual edition of the poster session of the 2nd Computer Science Workshop @ DIBRIS!]
"""
