url: https://docs-dibris.github.io
theme: just-the-docs
color_scheme: dark

title: DoCS
description: Dottorandi in Computer Science
logo: "/assets/images/docs-grad.png"
favicon-ico: "/favicon.ico"
search_enabled: false


callouts:
  highlight:
    title:
    color: yellow
  new:
    title: New!
    color: green
  important:
    title: Important
    color: blue
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple

aux_links:
  Follow us on Instagram!: https://www.instagram.com/docs.dibris/

ga_tracking: UA-2709176-10
ga_tracking_anonymize_ip: true
